### PR TITLE
Add list of related software.

### LINKED ISSUE #67: link to software using/implementing Demes in the docs
This would be as an advertisement that if you have, or write, a Demes file, that you can indeed use it for something. Probably as a third section on the introduction page, in alphabetical order. If it gets too long we can move it to its own page in the future.

* demes-python
* fwdpy11
* moments
* msprime (soon)
* stdpopsim (soon)

A one-line description of each might be nice too.

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #67.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Maybe split this up into sections of software *for* demes (demes-python, demes-draw, etc) and software that *uses* demes?

**Review by jeromekelleher — APPROVED** [review]
Looks great!

(maybe we add a note at the bottom saying "if you'd like to add your software to this list, please open a Pull Request"?)

**Comment by grahamgower** [comment]
> (maybe we add a note at the bottom saying "if you'd like to add your software to this list, please open a Pull Request"?)

There's a "click here" link at the top of the section which takes the user directly to a "edit this page in github, which has a markdown preview" (ie. https://github.com/popsim-consortium/demes-spec/edit/main/docs/introduction.md). Would you prefer it was linked under the list?

**Comment by jeromekelleher** [comment]
It's not so much the "how" I have in mind, it's just encouraging people to actually do it. I think we're a lot more used to open development that others, and they might not realise that we actually *want* them up update the list.

**Pull request merged**
