### PR TITLE
Add (invalid) test cases of proportions == 0.0

### PR DESCRIPTION
**Pull request by molpopgen**
See #166.
See also popsim-consortium/demes-python#576

### CODE REVIEW

**Comment by molpopgen** [comment]
@grahamgower -- go for it!

**Comment by molpopgen** [comment]
@grahamgower -- I just rebased this onto main so that CI works.

**Comment by grahamgower** [comment]
@molpopgen, could you please run your eye over the changes I added here? If you're ok with it, I think it can be merged.

**Comment by molpopgen** [comment]
LGTM but not sure why some changes concern selfing/cloning rates?

**Comment by grahamgower** [comment]
In the schema definitions, we have (a) `proportion` for ancestry proportions and pulse proportions, where `0 < proportion <= 1`, and (b) we have `rate` for migration rates, selfing/cloning, where `0 <= rate <= 1`. The code in the reference implementation instead used the term 'fraction' and this was used for both proportions and rates, so I removed 'fraction' in favour of using the same terms and definitions as the schema.

**Comment by molpopgen** [comment]
Seems like this one is ready to go!

**Pull request merged**
