### PR TITLE
Enforce deme start times are inf for root demes.

### LINKED ISSUE #53: Eforce root deme start times are inf.
https://github.com/popsim-consortium/demes-python/issues/169

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #53.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM. 

I'm curious about how all the noise in the json files happened, have you any theories there?

**Comment by grahamgower** [comment]
Yeah, I needed to update half a dozen from the YAML files, and got lazy so did a `for i in *.yaml; do python resolv_yaml.py $i > ... ; done`. So all the json files got recreated, and for some reason the ordering in the dict output is slightly different (I'm on python 3.9, maybe there's a change to the json module?).

**Comment by jeromekelleher** [comment]
> So all the json files got recreated, and for some reason the ordering in the dict output is slightly different (I'm on python 3.9, maybe there's a change to the json module?).

Ah, must be Python 3.9. I had thought the order would be canonical, but it doesn't matter.

**Comment by grahamgower** [comment]
I agree, the order should be canonical. And I don't see anything in the Python docs for `json.dump()` or `dataclasses.asdict()` that suggests relevant changes in either python 3.8 or 3.9. The dict order produced from `asdict()` should match the order of class attribute declarations. Maybe you created the resolved.json files, then the order of attribute declarations was shuffled before commiting?

**Comment by grahamgower** [comment]
Yep, the commit where the json files were added also has a different order for the attributes in the Graph. https://github.com/popsim-consortium/demes-spec/blob/ac784f1d35eb2c665b96fdf290812951588a5b85/reference_implementation/parser.py

**Comment by jeromekelleher** [comment]
Thanks for digging in - let's not worry about it.

**Pull request merged**
