### PR TITLE
Add subschema test.

### LINKED ISSUE #97: MDM schema should be a subschema of HDM
I'm sure we can check that this is true and add a test for that. A quick search brought up https://github.com/haggholm/is-json-schema-subset

### PR DESCRIPTION
**Pull request by grahamgower**
Closes #97.

---

This fails immediately. I think it's becase we have infinity in the schema, which is not really valid JSON.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
I like it - also addresses #70 right?

**Review by jeromekelleher — APPROVED** [review]

**Comment by grahamgower** [comment]
I'm not so sure about the `.inf` removal. If we really do define the spec in terms of JSONSchema, then we cannot have infinite values anywhere. They must all be strings.
 * We can't validate yaml files that contain `.inf`, because these are read into Python as float inf.
 * The parsers must all support the string "Infinity" in the YAML input too (including through the Builder API in demes-python).
 * We must only output the string "Infinity", even for YAML output.
* Confounding things, it seems that the python jsonschema library is quite happy to validate infinties. Other JSONSchema validators are unlikely to be so forgiving.

This all seems quite horrible.

**Comment by jeromekelleher** [comment]
I'd be strongly inclined to define things in terms of JSON - it's a well defined specification that's universally supported. If we have to have a bit of ickiness around infinities, then :shrug: If we go to defining things in terms of YAML, we lose the ability to formally define the schema, which is a major downside.

**Comment by grahamgower** [comment]
I agree here, I'm just not sure if we're opening a big can of worms...?

**Comment by jeromekelleher** [comment]
Well, let's get this much merge and see how much of a mess it makes if we try to remove .inf entirely.

**Comment by jeromekelleher** [comment]
LGTM

**Comment by grahamgower** [comment]
I rebased and fixed conflicts with the null changes, but I don't think we should merge this just yet. This should fail, because a large number of our test cases include `.inf`, which is no longer valid according to our schema. The jsonschema Python package just accepts python float `inf` values when it should not.

**Comment by grahamgower** [comment]
```
$ python
Python 3.9.5 (default, May 24 2021, 12:50:35)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonschema
>>> jsonschema.__version__
'3.2.0'
>>> jsonschema.validate(instance=float("inf"), schema={"type": "number"})
>>> jsonschema.validate(instance=float("nan"), schema={"type": "number"})
>>>

```

I don't think this will get fixed, as the NaN case has been raised previously: https://github.com/Julian/jsonschema/issues/357

I see this as a problem, because we need to state that infinity is *not* a valid number for some fields (e.g. `end_time`). Before this PR, this was done by saying `exclusiveMaximum: .inf`. jsonschema then correctly rejects inf.

```
>>> jsonschema.validate(instance=float("inf"), schema={"type": "number", "exclusiveMaximum": float("inf")})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/grg/.local/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: inf is greater than or equal to the maximum of inf

Failed validating 'exclusiveMaximum' in schema:
    {'exclusiveMaximum': inf, 'type': 'number'}

On instance:
    inf
```

So, either we accept that we'll have `.inf` in the schema, and then the schema isn't valid JSON, or alternately, we say: JSON itself doesn't allow infinity, so we don't need to specify an exclusiveMaximum as no input with a float `inf` could validate according to the schema. Only, jsonschema doesn't work like that, so we really would need to use a different validator.

**Comment by jeromekelleher** [comment]
Hmm, very tricky.

**Comment by jeromekelleher** [comment]
What would happen if we didn't specify the ranges of these values in JSONSchema and instead said it within the spec? The schema is just a framework anyway, there's loads of other stuff we're adding on afterwards.

**Comment by grahamgower** [comment]
> What would happen if we didn't specify the ranges of these values in JSONSchema and instead said it within the spec? The schema is just a framework anyway, there's loads of other stuff we're adding on afterwards.

That's probably a fair compromise. I just checked two other python libraries for validating schemas (https://horejsek.github.io/python-fastjsonschema/ and https://github.com/marksparkza/jschon), and they also validate float inf without respecting the JSON spec. We'll need to make it clear that validating a model against the schema is in no way sufficient to guarantee a valid model.


Can we also somehow accept float `inf` (and thus yaml `.inf`) in addition to string "Infinity"? Accepting a string is easy enough, but I feel very uneasy about trying to exclude float inf values (not least of which it would be very confusing for users).

**Comment by grahamgower** [comment]
[jsonschema-rs](https://github.com/Stranger6667/jsonschema-rs/tree/master/bindings/python) *does* do the right thing wrt infinity.
```
$ python
Python 3.9.5 (default, May 24 2021, 12:50:35)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonschema_rs
>>> validator = jsonschema_rs.JSONSchema({"type": "number"})
>>> validator.is_valid(3)
True
>>> validator.is_valid("a")
False
>>> validator.is_valid(float("inf"))
False
>>> validator.is_valid(float("nan"))
False
```

**Comment by jeromekelleher** [comment]
> Can we also somehow accept float inf (and thus yaml .inf) in addition to string "Infinity"? Accepting a string is easy enough, but I feel very uneasy about trying to exclude float inf values (not least of which it would be very confusing for users).

That seems like a reasonable compromise, but I guess we should check how some non-Python libraries JSON libraries take .inf etc. 

So the point here is to make sure that we're interoperable. If some Rust or C++ JSON library (say) doesn't like the values we're writing out, then that's bad.

**Comment by grahamgower** [comment]
I don't think we'll have a problem there, as we should continue using string "Infinity" when writing JSON. But I'd like to also be able to use `.inf` when writing YAML (because YAML supports infinite valued numbers). So what if the spec says: 
 * Parsers must support both string "Infinity" and float inf on input (even for input formats like YAML that support a proper inf).
 * Parsers should preferentially output float inf for output formats that support that (e.g. YAML), and output string "Infinity" for output formats that don't support inf (e.g. JSON).

This requires very little from the parser. Just convert string "Infinity" to float on input, and output string "Infinity" if supporting JSON output. On the other hand, if the string "Infinity" leaks into a serialisation format that has first-class support for infinite values, then it can still be read in by a conformant parser.

**Comment by jeromekelleher** [comment]
That sounds like an excellent plan.

**Comment by grahamgower** [comment]
I just double checked this, and I think it's consistent with what we decided last week. So I'm going to merge it.

**Pull request merged**
